Publish correct absolute URLs via STAC API
Previously, the STAC items were rendered without a self link.
If the source ingest provided relative links to resources, they
would be published directly via the STAC API, causing downstream
issues in pystac client:

> STACError: Relative path ../collection.json encountered without owner "self" link set.

This now converts all published links to absolute URLs, which
pystac client can use to navigate around the catalog.